### ISSUE TITLE
IFTT Not receiving any input from roam  

### ISSUE THREAD

**Issue by thomasqjohns** [mlava/json-webhooks#1]
If i click into a roam parent node and trigger the event. The event will trigger  correctly but IFTT will not receive any values for value 1 , Value2, Value3. 

I will look at the code to see if im doing something wrong or if maybe something changed on IFTT end.

The extension Roam to JSon we hook extension does work when triggered from the https://maker.ifttt.com/use/{key} page and putting a value in to there 

This example of text that i’m inputting 
![IMG_0909](https://user-images.githubusercontent.com/8973377/184901925-132c5993-87ac-4f99-aced-67aa4b1f97dc.jpeg)

This is print out of what IFTT received 

![IMG_0908](https://user-images.githubusercontent.com/8973377/184902130-b3582d03-dd2b-46d6-be4e-17ef4dd1161a.png)

**Comment by mlava** [comment]
Hi @thomasqjohns sorry it didn't work.
Could you please try to trigger it again and let me know if anything shows in your browser console?
IFTTT was the most flakey of the four options I tried, and only allows three variables. 

Also, is your webhook address exactly like this in the Roam Dept settings?

`https://maker.ifttt.com/trigger/roam_TODO/with/key/{long alphanum key}`

This is what I see when I try it with my webhook address:

![image](https://user-images.githubusercontent.com/6857790/185032848-60ca3097-e53e-4f7d-b345-d6f818099870.png)

Cheers,
Mark

**Comment by thomasqjohns** [comment]
My roam depo settings are https://maker.ifttt.com/trigger/Roam_TODO/json/with/key/{key}.
I believe the applet wouldn't trigger if the roam depo settings were wrong. I will try with lower case "roam_TODO" to see if that changes anything.  

Error from chrome console log 

![Screen Shot 2022-08-17 at 9 58 07 AM](https://user-images.githubusercontent.com/8973377/185172942-e5a571f0-e2b7-43a7-8914-f529070a7fb9.png)

error is referring to  line 61 in code 

 if (!WebhookURL.match("ifttt")) {
                        blocks['parentText'] = thisBlockInfo[":block/string"];
                    } else {
                        blocks['value1'] = thisBlockInfo[":block/string"];  this one returns null 
![Screen Shot 2022-08-17 at 10 07 04 AM](https://user-images.githubusercontent.com/8973377/185175119-b2d16abd-3b92-40fa-90ca-6004384dbfed.png)

**Comment by thomasqjohns** [comment]
@mlava also great job.. this is really useful

**Comment by thomasqjohns** [comment]
This is a different error which looks to be some sort of cors issue when fetching. I'm going to check that I have some value wrong but don't think that's it because if the roam depot values are wrong it doesn't run at all. 

The json values are being sent properly in post command but iftt does not get them 

![Screen Shot 2022-08-17 at 10 20 00 AM](https://user-images.githubusercontent.com/8973377/185178049-52ce249d-43b7-4af6-88b3-f34ad6d570b5.png)

**Comment by mlava** [comment]
Does the last one mean you got the extension to work? Or are you still having both issues?
For the first one, make sure you've clicked into the parent block with 'Testing json webhooks' as the text. It needs to be focused (cursor in the block) to trigger properly.
For the second one, thanks for raising it.
It's now fixed in https://github.com/mlava/json-webhooks/commit/90319eb9b855eef4d0475aa0f08b21f5b9d64d36
Hopefully it will be approved for Roam Depot soon.

**Comment by thomasqjohns** [comment]
Awesome.. thanks a lot. That was really fast. Maybe I’ll try running the code in my roam but will probably wait for roam depot to approve. Should we close this issue after they approve it or close now and reopen if theres another issue after they approve it

**Comment by mlava** [comment]
It just got merged. Let's keep this issue open, you can test it and confirm.
Cheers!

**Comment by thomasqjohns** [comment]
So i've been trying the new version.. I get no errors in the console now but IFTT not still not receiving values.

Possible reasons:

Do you have the pro version of IFTT? I am running free version. Maybe there is a difference in how things work on different versions.

Is it possible that IFTT is looking for {{Value1}} and you are sending "value1" to it instead? The difference being the uppercase V ?

The only ingredients available are Value1 , Value2, Value3 and not value1 value2 value3. I've tried just typing that in and it doesn't work. 


![Screen Shot 2022-08-22 at 10 50 19 AM](https://user-images.githubusercontent.com/8973377/185964033-bce34051-28fb-42af-9c34-39419a75e104.png)

what Roam to json webhooks is sending 

         value1=put%20site%20on%20hacker%20news&value2=undefined&value3=undefine

I don't know if IFTT makes Value1 and value1 into the same thing though.

**Comment by mlava** [comment]
> So i've been trying the new version.. I get no errors in the console now but IFTT not still not receiving values.
> 
> Possible reasons:
> 
> Do you have the pro version of IFTT? I am running free version. Maybe there is a difference in how things work on different versions.
> 
> Is it possible that IFTT is looking for {{Value1}} and you are sending "value1" to it instead? The difference being the uppercase V ?
> 
> The only ingredients available are Value1 , Value2, Value3 and not value1 value2 value3. I've tried just typing that in and it doesn't work.
> 
> ![Screen Shot 2022-08-22 at 10 50 19 AM](https://user-images.githubusercontent.com/8973377/185964033-bce34051-28fb-42af-9c34-39419a75e104.png)
> 
> what Roam to json webhooks is sending
> 
> ```
>      value1=put%20site%20on%20hacker%20news&value2=undefined&value3=undefine
> ```
> 
> I don't know if IFTT makes Value1 and value1 into the same thing though.

Damn.
I'm not on Pro, just the basic free version.
I will try to troubleshoot once they're back up, but at the moment they're running maintenance. 
I know that my trials last week after the CORS issue fix showed tasks arriving in my calendar with values intact (RR -> IFTTT -> gCal) so it seemed to be working for me.
I'll get back to you.

**Comment by thomasqjohns** [comment]
I’m going RR -> IFTTT-> reminders and will try gcal to see if that works

@intensethomas
Believe in the you that believes in you
www. ( http://www.bitinow.com ) moonbase5.com ( http://moonbase5.com )
My new book Spiral Dynamics in Action ( http://a.co/fg1jHFt )
Connect with me on LinkedIn https://www.linkedin.com/in/thomasqjohns

Sent via Superhuman iOS ( ***@***.*** )

**Comment by mlava** [comment]
This is what I'm seeing when I trigger the extension:

![image](https://user-images.githubusercontent.com/6857790/186132379-6dce3622-7d03-4fef-a3cd-70046808be6c.png)

**Comment by mlava** [comment]
Closing as no further comments for 20d. Please open a new issue if needed. Cheers!
